# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://reubano.github.com
title: reubano
#subtitle: My nothings on technology, finance, and life
author: Reuben Cummings
simple_search: http://google.com/search
description: 'My personal website covering finance, technology, mac osx, and, web application development'
keywords: mac, osx, python, php, pear, linux, investing, asset allocation, portfolio performance, risk, return, web application development, restful api, flask, node

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: reubano@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: []
custom_asides: [custom/asides/popular_posts.html,asides/github.html, asides/twitter.html, asides/googleplus.html]
blog_index_asides: [asides/recent_posts.html, custom/asides/popular_posts.html, asides/twitter.html]
post_asides: [custom/asides/related_posts.html, asides/recent_posts.html, custom/asides/popular_posts.html]
home_asides: [custom/asides/about.html, asides/recent_posts.html, custom/asides/popular_posts.html]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: reubano
github_repo_count: 3
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: reubano
twitter_tweet_count: 3
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: reubano
googleplus_hidden: true

# Pinboard
#pinboard_user: reubano
#pinboard_count: 3

# Delicious
#delicious_user:
#delicious_count: 3

# Disqus Comments
#disqus_short_name: reubano
#disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-35222393-1

# Facebook Like
facebook_like: true

# Google +1
google_plus_one: true
google_plus_one_size: medium
